# Build stage
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install --only=production

# Production stage
FROM node:20-alpine
WORKDIR /app
COPY --from=build /app .
COPY src ./src 
COPY prisma ./prisma 
RUN npx prisma generate 

# Declare build arguments
ARG DATABASE_URL
ARG JWT_SECRET

# Set environment variables from build arguments
ENV DATABASE_URL=$DATABASE_URL
ENV JWT_SECRET=$JWT_SECRET

EXPOSE 5000
CMD ["node", "src/server.js"]